name: gaussmart
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - attr=2.5.1
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - blessed=1.19.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - cairo=1.18.2
  - ceres-solver=2.2.0
  - cuda-cccl_linux-64=12.1.109
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cudart-dev_linux-64=12.1.105
  - cuda-cudart-static=12.1.105
  - cuda-cudart-static_linux-64=12.1.105
  - cuda-cudart_linux-64=12.1.105
  - cuda-driver-dev_linux-64=12.1.105
  - cuda-nvcc=12.1.105
  - cuda-nvcc-dev_linux-64=12.1.105
  - cuda-nvcc-impl=12.1.105
  - cuda-nvcc-tools=12.1.105
  - cuda-nvcc_linux-64=12.1.105
  - cuda-version=12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - eigen=3.4.0
  - expat=2.7.1
  - flann=1.9.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeimage=3.18.0
  - freetype=2.12.1
  - gcc_impl_linux-64=12.4.0
  - gcc_linux-64=12.4.0
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gflags=2.2.2
  - glew=2.1.0
  - glib=2.82.2
  - glib-tools=2.82.2
  - glog=0.7.1
  - gmp=6.3.0
  - gpustat=1.1.1
  - graphite2=1.3.13
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - gxx_impl_linux-64=12.4.0
  - gxx_linux-64=12.4.0
  - harfbuzz=10.2.0
  - hdf5=1.14.4
  - icu=75.1
  - imath=3.1.12
  - jxrlib=1.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libaec=1.1.3
  - libamd=3.3.3
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libboost=1.86.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcap=2.71
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcolamd=3.3.4
  - libcups=2.3.3
  - libcurl=8.11.1
  - libcxsparse=4.4.1
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-devel_linux-64=12.4.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libklu=2.3.5
  - liblapack=3.9.0
  - libldl=3.3.2
  - libllvm19=19.1.7
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.28
  - libopus=1.3.1
  - libparu=1.0.0
  - libpciaccess=0.18
  - libpng=1.6.46
  - libpq=17.3
  - libraw=0.21.3
  - librbio=4.3.4
  - libsanitizer=12.4.0
  - libsndfile=1.2.2
  - libspex=3.2.1
  - libspqr=4.3.4
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=12.4.0
  - libstdcxx-ng=14.2.0
  - libsuitesparseconfig=7.8.3
  - libsystemd0=257.2
  - libtiff=4.7.0
  - libumfpack=6.3.5
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - metis=5.1.0
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nspr=4.36
  - nss=3.108
  - nvidia-ml-py=12.560.30
  - openexr=3.3.2
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.2
  - pcre2=10.44
  - pip=25.2
  - pixman=0.44.2
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - python=3.10.18
  - readline=8.2
  - setuptools=80.9.0
  - sqlite=3.32.3
  - suitesparse=7.8.3
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - typing_extensions=4.12.2
  - unzip=6.0
  - vlfeat=0.9.21
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxxf86vm=1.1.6
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - accelerate==1.10.0
      - addict==2.4.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cmake==4.1.0
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diff-surfel-rasterization==0.0.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flask==3.1.1
      - fonttools==4.59.1
      - fsspec==2025.7.0
      - hf-xet==1.1.7
      - huggingface-hub==0.34.4
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lpips==0.1.4
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mediapy==1.1.2
      - mpmath==1.3.0
      - narwhals==2.1.2
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - open3d==0.18.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - plotly==6.3.0
      - plyfile==1.1.2
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.4
      - retrying==1.4.2
      - rpds-py==0.27.0
      - safetensors==0.6.2
      - scikit-image==0.21.0
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - segment-anything==1.0
      - simple-knn==0.0.0
      - six==1.17.0
      - stack-data==0.6.3
      - supervision==0.26.1
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tokenizers==0.21.4
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.66.2
      - traitlets==5.14.3
      - transformers==4.56.0.dev0
      - trimesh==4.3.2
      - triton==3.1.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - zipp==3.23.0
